### PR TITLE
New messages for FaceMask and 2D ROI

### PR DESCRIPTION
**Pull request by francescotonini**
This PR proposes the introduction of two messages to this package:
- `RegionOfInterest2D` represents a 2D ROI with an associated confidence. This message is similar to `PointOfInterest2D`.
- `FaceMask` describes whether a person is wearing a face mask. The structure of the message allows for future extensions, like the introduction of additional mask classes (e.g. "wearing a mask not covering the nose").

Both messages contain a header field to allow easy synchronisation with other ROS topics.

### CODE REVIEW

**Comment by severin-lemaignan** [comment]
Thanks for the PR!

- regarding `RegionOfInterest2D`: why not using [`sensor_msgs/RegionOfInterest`](http://docs.ros.org/en/noetic/api/sensor_msgs/html/msg/RegionOfInterest.html)
- for `FaceMask`, I think this is too specific to be added to `hri_msgs`. Better to keep it in a specific, project-related, set of message (or to design a more generic 'PersonAttributes` that could also cover hats, glasses, color of cloth, etc...)

**Comment by francescotonini** [comment]
Thanks for the reply!

> * regarding `RegionOfInterest2D`: why not using [`sensor_msgs/RegionOfInterest`](http://docs.ros.org/en/noetic/api/sensor_msgs/html/msg/RegionOfInterest.html)

The sensor_msgs implementation doesn't include a `header`  to ease synchronization with other topics, doesn't include a value to express the confidence of the bounding box, nor it allows for normalized coordinates in the [0, 1] range. Besides, I think this message is a nice addition to the package given the presence of a similar message for 2D points.

> * for `FaceMask`, I think this is too specific to be added to `hri_msgs`. Better to keep it in a specific, project-related, set of message (or to design a more generic 'PersonAttributes` that could also cover hats, glasses, color of cloth, etc...)

I like the idea of the `PersonAttributes` message, it would be a welcome addition to `hri_msgs`. I removed the `FaceMask` message from this PR.

**Comment by severin-lemaignan** [comment]
I agree with your point about `RegionOfInterest2D`. Let's add it (even though, ideally, it should be integrated to `sensor_msgs` -> once merged here, maybe you can open a issue in the `sensor_msgs` repo to offer to move both `PointOfInterest2D` and `regionOfInterest2D` there?)

Three requests:
- can you squash the 'FaceMask' message commits so that they do not appear at all in the PR?
- can you add a `Header` to `PointOfInterest2D`?
- maybe we should rename both `PointOfInterest2D` and `RegionOfInterest2D` into `NormalizedPointOfInterest2D` and `NormalizedRegionOfInterest2D` (to distinguish eg `RegionOfInterest2D` from `sensor_msgs/RegionOfInterest`). What do you think?

**Comment by francescotonini** [comment]
I agree, I addressed all your requests in the latest commits.

**Comment by severin-lemaignan** [comment]
I think you also need to update the CMakeLists to generate the messages

**Comment by francescotonini** [comment]
It should be updated, in the “rename” commit I updated CMakeLists as well.

**Comment by severin-lemaignan** [comment]
ok, I missed that change. Great. Let's merge.

**Pull request merged**
